import type { RegionHotspot, RegionId } from './data/regionTypes';

/** Curated landmarks — small strings to keep chunks light. */
export const REGION_LANDMARK_HOTSPOTS: Readonly<Partial<Record<RegionId, readonly RegionHotspot[]>>> = {
  kanto: [
    {
      id: 'kanto-pallet',
      kind: 'city',
      label: 'Pallet Town',
      map: { x: 14, y: 86 },
      lore: 'Quiet seaside beginnings — Professor Oak’s lab waits up the path.',
      linkedRouteId: 'kanto-route-1',
      atmosphereTease: 'Salt air and slow afternoons before the journey widens.',
    },
    {
      id: 'kanto-pewter',
      kind: 'gym',
      label: 'Pewter Gym',
      map: { x: 34, y: 22 },
      lore: 'Stone badges and stubborn lines — the first real wall for new trainers.',
      progressionTease: 'Rock-solid defense teaches type respect early.',
    },
    {
      id: 'kanto-saffron',
      kind: 'city',
      label: 'Saffron City',
      map: { x: 52, y: 36 },
      lore: 'Psychic dojos and corporate glass — the crossroads of Kanto’s spine.',
      linkedRouteId: 'kanto-route-5',
      atmosphereTease: 'Urban hum undercuts every duel.',
    },
    {
      id: 'kanto-lavender',
      kind: 'landmark',
      label: 'Lavender Town',
      map: { x: 78, y: 40 },
      lore: 'Soft bells and long shadows — a slower tempo between tunnels and peaks.',
      linkedRouteId: 'kanto-rock-tunnel',
      habitatTease: 'Spirits and sound carry differently in the hush.',
    },
    {
      id: 'kanto-cerulean-cave',
      kind: 'cave',
      label: 'Cerulean Cave',
      map: { x: 62, y: 18 },
      lore: 'Deep blue chambers for trainers who already proved the league.',
      progressionTease: 'Post-game pressure — every step is earned.',
    },
    {
      id: 'kanto-indigo',
      kind: 'legendary',
      label: 'Indigo Plateau',
      map: { x: 54, y: 10 },
      lore: 'The league’s gates — wind, crowd roar, and the final climb.',
      linkedRouteId: 'kanto-victory-road',
      atmosphereTease: 'Cold stone and bright arena lights.',
    },
  ],
  johto: [
    {
      id: 'johto-new-bark',
      kind: 'city',
      label: 'New Bark Town',
      map: { x: 82, y: 78 },
      lore: 'Riverside calm before Johto opens into gold fields and bell towers.',
      linkedRouteId: 'johto-route-29',
      atmosphereTease: 'Morning mist on the water.',
    },
    {
      id: 'johto-goldenrod',
      kind: 'city',
      label: 'Goldenrod City',
      map: { x: 44, y: 44 },
      lore: 'Department stores and underground rails — commerce as geography.',
      progressionTease: 'Mid-game pivot where teams diversify fast.',
    },
    {
      id: 'johto-ecruteak',
      kind: 'landmark',
      label: 'Ecruteak Dance Theater',
      map: { x: 58, y: 30 },
      lore: 'Kimono steps and old myths — fire and water stories told in motion.',
      atmosphereTease: 'Lantern light on lacquered floors.',
    },
  ],
  hoenn: [
    {
      id: 'hoenn-littleroot',
      kind: 'city',
      label: 'Littleroot Town',
      map: { x: 22, y: 82 },
      lore: 'Lab trucks and pollen-heavy air — Hoenn’s rhythm starts tropical.',
      linkedRouteId: 'hoenn-route-101',
      habitatTease: 'Early routes teem with humid-route species.',
    },
    {
      id: 'hoenn-mauville',
      kind: 'city',
      label: 'Mauville City',
      map: { x: 50, y: 48 },
      lore: 'Bikes, plazas, and neon arcs — a crossroads wired for contests and battles.',
      progressionTease: 'Electric gym energy hums under the arcade glow.',
    },
    {
      id: 'hoenn-sky-pillar',
      kind: 'legendary',
      label: 'Sky Pillar',
      map: { x: 72, y: 20 },
      lore: 'Wind-cut columns where the sky feels negotiable.',
      atmosphereTease: 'Thin air and ancient stone.',
    },
  ],
  sinnoh: [
    {
      id: 'sinnoh-twinleaf',
      kind: 'city',
      label: 'Twinleaf Town',
      map: { x: 38, y: 82 },
      lore: 'Twin groves and soft snow rumors — Sinnoh opens polite, then deep.',
      linkedRouteId: 'sinnoh-route-201',
      weatherHint: 'Winter whispers even on warm days.',
      atmosphereTease: 'Snowfield light on quiet fences.',
    },
    {
      id: 'sinnoh-spear-pillar',
      kind: 'legendary',
      label: 'Spear Pillar',
      map: { x: 48, y: 14 },
      lore: 'Mythic altitude where legends feel mathematically close.',
      progressionTease: 'Late-game myth density spikes here.',
    },
  ],
  unova: [
    {
      id: 'unova-nuvema',
      kind: 'city',
      label: 'Nuvema Town',
      map: { x: 86, y: 72 },
      lore: 'Ocean labs and brisk wind — Unova’s story boards the next ferry.',
      linkedRouteId: 'unova-route-1',
      atmosphereTease: 'Harbor gulls and glass towers on the horizon.',
    },
    {
      id: 'unova-nacrene',
      kind: 'landmark',
      label: 'Nacrene City',
      map: { x: 32, y: 52 },
      lore: 'Warehouses turned galleries — history stacked like pallets.',
      habitatTease: 'Bug and normal lines love the edge of the woods.',
    },
  ],
  kalos: [
    {
      id: 'kalos-vaniville',
      kind: 'city',
      label: 'Vaniville Town',
      map: { x: 18, y: 80 },
      lore: 'Courtyard hedges and couture roofs — fashion and battle share a tailor.',
      linkedRouteId: 'kalos-route-2',
      atmosphereTease: 'Pastel mornings before mega-city sprawl.',
    },
    {
      id: 'kalos-lumiose',
      kind: 'city',
      label: 'Lumiose City',
      map: { x: 50, y: 38 },
      lore: 'Radial boulevards and prism light — Kalos reads like a runway.',
      progressionTease: 'Mid-game rotations tighten team coverage tests.',
    },
  ],
  alola: [
    {
      id: 'alola-melemele',
      kind: 'island',
      label: 'Melemele Island',
      map: { x: 32, y: 68 },
      lore: 'Sun-washed shores and trial-friendly paths — the Alola journey learns its pace here.',
      habitatTease: 'Coastal species trade niches with upland cousins.',
    },
    {
      id: 'alola-akala',
      kind: 'island',
      label: 'Akala Island',
      map: { x: 52, y: 50 },
      lore: 'Brooklet streams and volcanic perfume — humidity carries sound farther.',
      linkedRouteId: 'alola-brooklet-hill',
      weatherHint: 'Warm rain on short notice.',
    },
    {
      id: 'alola-ulaula',
      kind: 'island',
      label: 'Ula’ula Island',
      map: { x: 72, y: 36 },
      lore: 'Mountains and observatories — colder air, sharper stars, slower speeches.',
      linkedRouteId: 'alola-mount-lanakila',
      atmosphereTease: 'Snow dust mixes with volcanic grit.',
    },
    {
      id: 'alola-poni',
      kind: 'island',
      label: 'Poni Island',
      map: { x: 42, y: 26 },
      lore: 'Trial gardens and coastal cliffs — the map’s quiet exclamation point.',
      linkedRouteId: 'alola-ultra-space',
      progressionTease: 'Late-game density without mainland sprawl.',
    },
    {
      id: 'alola-hauoli',
      kind: 'city',
      label: 'Hau’oli City',
      map: { x: 24, y: 78 },
      lore: 'Beachfront plazas and trial cheers — island time with sharp edges.',
      linkedRouteId: 'alola-route-1',
      habitatTease: 'Coastal species trade places with volcanic upslope cousins.',
    },
    {
      id: 'alola-lanakila-summit',
      kind: 'legendary',
      label: 'Mount Lanakila',
      map: { x: 62, y: 22 },
      lore: 'Ice crowns the league here — thin air, loud crowds, quiet snow.',
      linkedRouteId: 'alola-mount-lanakila',
      progressionTease: 'Victory Road energy without the mainland template.',
    },
  ],
  galar: [
    {
      id: 'galar-postwick',
      kind: 'city',
      label: 'Postwick Town',
      map: { x: 28, y: 84 },
      lore: 'Cottage smoke and stadium rumors — Galar’s pitch is always visible.',
      linkedRouteId: 'galar-route-1',
      atmosphereTease: 'Wind that tastes like turf and brass bands.',
    },
    {
      id: 'galar-hammerlocke',
      kind: 'gym',
      label: 'Hammerlocke',
      map: { x: 44, y: 36 },
      lore: 'Dragon gym silhouettes against castle walls — power as skyline.',
      progressionTease: 'Type spikes punish linear teams.',
    },
  ],
  paldea: [
    {
      id: 'paldea-cabo',
      kind: 'city',
      label: 'Cabo Poco',
      map: { x: 26, y: 84 },
      lore: 'Olive light on stucco — the academy’s bus leaves without fanfare.',
      linkedRouteId: 'paldea-poco-path',
      atmosphereTease: 'Open world hum under every picnic.',
    },
    {
      id: 'paldea-academy',
      kind: 'landmark',
      label: 'Academy Mesas',
      map: { x: 46, y: 58 },
      lore: 'Classes, titans, and crystal overlays — Paldea stacks systems on one map.',
      progressionTease: 'Terastal reshapes mid-fight tempo.',
    },
  ],
};
